version: '3.8'

services:
  web:
    build: .
    container_name: lacevista-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/lacevistaDB
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: lacevista-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
